# Generated by Django 4.2 on 2024-04-22 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="patronymic",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 4, 22, 9, 51, 43, 288996, tzinfo=datetime.timezone.utc
                ),
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="login",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 4, 22, 9, 51, 49, 883964, tzinfo=datetime.timezone.utc
                ),
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 4, 22, 9, 51, 57, 302242, tzinfo=datetime.timezone.utc
                ),
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("coach", "coach"), ("client", "client")],
                default="client",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
