# Generated by Django 4.2 on 2024-05-19 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_phonenumberverifysms_emailverifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bust", models.PositiveIntegerField(default=0)),
                ("biceps", models.PositiveIntegerField(default=0)),
                ("hip", models.PositiveIntegerField(default=0)),
                ("calf", models.PositiveIntegerField(default=0)),
                ("waist", models.PositiveIntegerField(default=0)),
                ("forearm", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "обьем тела",
                "verbose_name_plural": "Обьем тела",
            },
        ),
        migrations.CreateModel(
            name="ExternalIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_steps_per_day", models.PositiveBigIntegerField(default=0)),
                ("amount_of_KCAL_per_day", models.PositiveIntegerField(default=0)),
                ("proteins", models.PositiveIntegerField(default=0)),
                ("fats", models.PositiveIntegerField(default=0)),
                ("carbohydrates", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "внешний показатель",
                "verbose_name_plural": "Внешние показатели",
            },
        ),
        migrations.CreateModel(
            name="PhysicalIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "физические показатели",
                "verbose_name_plural": "Физические показатели",
            },
        ),
        migrations.CreateModel(
            name="UserStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_volumes", models.ManyToManyField(to="users.bodyvolume")),
                (
                    "external_indicators",
                    models.ManyToManyField(to="users.externalindicators"),
                ),
                (
                    "physical_indicators",
                    models.ManyToManyField(to="users.physicalindicators"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "статистику пользователя",
                "verbose_name_plural": "Статистика пользователя",
            },
        ),
        migrations.AddField(
            model_name="physicalindicators",
            name="user_statistics",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userstatistic"
            ),
        ),
        migrations.AddField(
            model_name="externalindicators",
            name="user_statistics",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userstatistic"
            ),
        ),
        migrations.AddField(
            model_name="bodyvolume",
            name="user_statistics",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userstatistic"
            ),
        ),
    ]
