# Generated by Django 4.2 on 2024-06-07 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_bodyvolume_externalindicators_physicalindicators_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "физические показатели",
                "verbose_name_plural": "Физические показатели",
            },
        ),
        migrations.RenameModel(
            old_name="ExternalIndicators",
            new_name="ExternalIndicator",
        ),
        migrations.RemoveField(
            model_name="userstatistic",
            name="body_volumes",
        ),
        migrations.RemoveField(
            model_name="userstatistic",
            name="external_indicators",
        ),
        migrations.RemoveField(
            model_name="userstatistic",
            name="physical_indicators",
        ),
        migrations.RemoveField(
            model_name="userstatistic",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bodyvolume",
            name="user_statistics",
        ),
        migrations.RemoveField(
            model_name="externalindicator",
            name="user_statistics",
        ),
        migrations.AddField(
            model_name="bodyvolume",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalindicator",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PhysicalIndicators",
        ),
        migrations.DeleteModel(
            name="UserStatistic",
        ),
    ]
