# Generated by Django 4.2 on 2024-06-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_physicalindicator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodyvolume",
            name="biceps",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bodyvolume",
            name="bust",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bodyvolume",
            name="calf",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bodyvolume",
            name="forearm",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bodyvolume",
            name="hip",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bodyvolume",
            name="waist",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="externalindicator",
            name="amount_of_KCAL_per_day",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="externalindicator",
            name="carbohydrates",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="externalindicator",
            name="fats",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="externalindicator",
            name="proteins",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="physicalindicator",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
